### ISSUE TITLE
Question regarding time format

### ISSUE THREAD

**Issue by Timppali** [allquixotic/encuum#12] opened 2023-02-19 11:46 UTC
I have a question regarding the time format of the databases that are generated. If the post_time for example says 1388229358, how can I transform that into the standard format with the date and time? Basically I'm not sure what this time format is based on.

**Comment by allquixotic** [comment] 2023-02-19 17:08
Times in the database are directly taken from Enjin's API; they are not transformed or processed by encuum in any way. They appear to be based on the 64-bit UNIX time, which is the number of seconds elapsed since January 1, 1970. See https://en.wikipedia.org/wiki/Unix_time and https://www.unixtimestamp.com/index.php

Since this is not a bug with encuum, closing the issue.

**Closed by allquixotic** 2023-02-19 17:08 UTC
